### ISSUE TITLE
httpotion from master branch fails to compile on elixir 1.3.0

### ISSUE THREAD

**Issue by rlb3** [edgurgel/httpoison#148]
```
== Compilation error on file lib/httpotion.ex ==
** (ArgumentError) Access is not a protocol
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    lib/httpotion.ex:292: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by edgurgel** [comment]
Wrong project: https://github.com/myfreeweb/httpotion
